# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Text-RecordDeduper
version:      0.01
version_from: lib/Text/RecordDeduper.pm
installdirs:  site
requires:
    Text::RecordParser:            0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
